language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get github.com/modocache/gover
  - go get -t -v ./...

script:
  - go test -v ./...
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
  - gover . coverprofile.txt

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverprofile.txt
